{"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/voucherDiscountTotal","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"s:20TicketmasterPurchase15TMPurchaseOrderC20voucherDiscountTotalSo15NSDecimalNumberCvp","title":"voucherDiscountTotal","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"voucherDiscountTotal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDecimalNumber","preciseIdentifier":"c:objc(cs)NSDecimalNumber"}],"symbolKind":"property","role":"symbol","modules":[{"name":"TicketmasterPurchase"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/voucherdiscounttotal"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"voucherDiscountTotal"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","kind":"typeIdentifier","text":"NSDecimalNumber"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/ticketmasterpurchase","title":"TicketmasterPurchase"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder":{"abstract":[{"type":"text","text":"A data structure that represents a purchased order"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TMPurchaseOrder"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder","role":"symbol","type":"topic","title":"TMPurchaseOrder","kind":"symbol","navigatorTitle":[{"text":"TMPurchaseOrder","kind":"identifier"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseOrder/voucherDiscountTotal":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"voucherDiscountTotal","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDecimalNumber","text":"NSDecimalNumber","kind":"typeIdentifier"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchaseorder\/voucherdiscounttotal","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseOrder\/voucherDiscountTotal","role":"symbol","type":"topic","title":"voucherDiscountTotal"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/title","op":"replace","value":"TMPurchaseOrder"},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/fragments","op":"replace","value":[{"kind":"identifier","text":"TMPurchaseOrder"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseOrder\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TMPurchaseOrder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}