{"kind":"symbol","abstract":[{"type":"text","text":"A UIViewController that allows Ticketmaster Checkout"}],"metadata":{"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseWebsiteConfiguration","kind":"typeIdentifier","text":"TMPurchaseWebsiteConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"discoveryEvent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:24TicketmasterDiscoveryAPI0B5EventV","kind":"typeIdentifier","text":"DiscoveryEvent"},{"kind":"text","text":"?)"}],"roleHeading":"Initializer","title":"init(configuration:discoveryEvent:)","externalID":"s:20TicketmasterPurchase30TMPurchaseNavigationControllerC13configuration14discoveryEventAcA0C20WebsiteConfigurationC_0A12DiscoveryAPI0kH0VSgtcfc","modules":[{"name":"TicketmasterPurchase"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/init(configuration:discoveryEvent:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/init(configuration:discoveryevent:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TMPurchaseWebsiteConfiguration","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration","preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseWebsiteConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"discoveryEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:24TicketmasterDiscoveryAPI0B5EventV","text":"DiscoveryEvent"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object that contains the various website\/club-site configuration settings. See "},{"type":"codeVoice","code":"TMPurchaseWebsiteConfiguration"},{"type":"text","text":" object for more details."}]}],"name":"configuration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional "},{"code":"DiscoveryEvent","type":"codeVoice"},{"type":"text","text":" object to provide information about an event. If not provided, the "},{"code":"DiscoveryEvent","type":"codeVoice"},{"type":"text","text":" will be automatically fetched according to the identifer indicated in the configuration."}]}],"name":"discoveryEvent"}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"Creates a presentable "},{"type":"codeVoice","code":"TMPurchaseNavigationController"},{"type":"text","text":" for the specified "},{"type":"codeVoice","code":"TMPurchaseWebsiteConfiguration"},{"type":"text","text":"."}],"type":"paragraph"},{"type":"aside","name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"Do not initialize instances of ","type":"text"},{"code":"TMPurchaseNavigationController","type":"codeVoice"},{"text":" before setting an API key in ","type":"text"},{"code":"TicketmasterPurchase.apiKey","type":"codeVoice"},{"text":".","type":"text"}]}],"style":"important"}]}],"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController/init(configuration:discoveryEvent:)":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController\/init(configuration:discoveryEvent:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TMPurchaseWebsiteConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@TicketmasterPurchase@objc(cs)TMPurchaseWebsiteConfiguration"},{"text":", ","kind":"text"},{"text":"discoveryEvent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DiscoveryEvent","kind":"typeIdentifier","preciseIdentifier":"s:24TicketmasterDiscoveryAPI0B5EventV"},{"text":"?)","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller\/init(configuration:discoveryevent:)","title":"init(configuration:discoveryEvent:)","abstract":[{"text":"A UIViewController that allows Ticketmaster Checkout","type":"text"}],"role":"symbol"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"type":"topic","url":"\/documentation\/ticketmasterpurchase","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","abstract":[],"kind":"symbol","title":"TicketmasterPurchase","role":"collection"},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseNavigationController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPurchaseNavigationController","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"A navigation controller (view controller) that allows users to select and purchase tickets to a Ticketmaster Event.","type":"text"}],"url":"\/documentation\/ticketmasterpurchase\/tmpurchasenavigationcontroller","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseNavigationController","title":"TMPurchaseNavigationController","type":"topic","navigatorTitle":[{"text":"TMPurchaseNavigationController","kind":"identifier"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchaseWebsiteConfiguration":{"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchaseWebsiteConfiguration","url":"\/documentation\/ticketmasterpurchase\/tmpurchasewebsiteconfiguration","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPurchaseWebsiteConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"TMPurchaseWebsiteConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Class used to configure behavior of website Event Details Page (EDP) and Cart"}],"kind":"symbol","title":"TMPurchaseWebsiteConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/title","value":"TMPurchaseNavigationController"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/fragments","value":[{"text":"TMPurchaseNavigationController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseNavigationController\/navigatorTitle","value":[{"kind":"identifier","text":"TMPurchaseNavigationController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseWebsiteConfiguration\/title","value":"TMPurchaseWebsiteConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseWebsiteConfiguration\/fragments","value":[{"text":"TMPurchaseWebsiteConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchaseWebsiteConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"TMPurchaseWebsiteConfiguration"}]}]}]}