{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/configurationprovider"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"s:26TicketmasterAuthentication29TMApigeeConfigurationProviderP","kind":"typeIdentifier","text":"TMApigeeConfigurationProvider"}]}]}],"metadata":{"title":"configurationProvider","modules":[{"name":"TicketmasterDiscoveryAPI"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configurationProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:26TicketmasterAuthentication29TMApigeeConfigurationProviderP","text":"TMApigeeConfigurationProvider","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property","externalID":"s:24TicketmasterDiscoveryAPI011TMDiscoveryC0C21configurationProvider0A14Authentication021TMApigeeConfigurationF0_pvp","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/configurationProvider","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI","doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI"]]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Apigee config provider (default: ","type":"text"},{"type":"codeVoice","code":"TMAuthentication.shared"}],"references":{"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI/configurationProvider":{"abstract":[{"type":"text","text":"Apigee config provider (default: "},{"type":"codeVoice","code":"TMAuthentication.shared"}],"title":"configurationProvider","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi\/configurationprovider","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI\/configurationProvider","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configurationProvider","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TMApigeeConfigurationProvider","kind":"typeIdentifier","preciseIdentifier":"s:26TicketmasterAuthentication29TMApigeeConfigurationProviderP"}]},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI":{"abstract":[],"url":"\/documentation\/ticketmasterdiscoveryapi","title":"TicketmasterDiscoveryAPI","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI","role":"collection","type":"topic"},"doc://com.ticketmaster.TicketmasterDiscoveryAPI/documentation/TicketmasterDiscoveryAPI/TMDiscoveryAPI":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMDiscoveryAPI","kind":"identifier"}],"navigatorTitle":[{"text":"TMDiscoveryAPI","kind":"identifier"}],"abstract":[{"text":"A class that stores the global configuration for the TicketmasterDiscoveryAPI SDK","type":"text"}],"title":"TMDiscoveryAPI","identifier":"doc:\/\/com.ticketmaster.TicketmasterDiscoveryAPI\/documentation\/TicketmasterDiscoveryAPI\/TMDiscoveryAPI","url":"\/documentation\/ticketmasterdiscoveryapi\/tmdiscoveryapi"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/title","op":"replace","value":"TMDiscoveryAPI"},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/fragments","op":"replace","value":[{"text":"TMDiscoveryAPI","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterDiscoveryAPI~1documentation~1TicketmasterDiscoveryAPI~1TMDiscoveryAPI\/navigatorTitle","op":"replace","value":[{"text":"TMDiscoveryAPI","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}