{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/disableUFCLoginManagement"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"TicketmasterPurchase"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableUFCLoginManagement"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"roleHeading":"Instance Property","role":"symbol","title":"disableUFCLoginManagement","externalID":"s:20TicketmasterPurchase10TMPurchaseC25disableUFCLoginManagementSbvp","symbolKind":"property"},"sections":[],"variants":[{"paths":["\/documentation\/ticketmasterpurchase\/tmpurchase\/disableufcloginmanagement"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase"]]},"kind":"symbol","abstract":[{"type":"text","text":"Disable UFC login management within the "},{"code":"TicketmasterPurchase SDK","type":"codeVoice"},{"type":"text","text":", the integrating App will handle UFC calls made by the website"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableUFCLoginManagement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Values:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"false (default) = "},{"type":"codeVoice","code":"PurchaseSDK"},{"type":"text","text":" will provide feedback directly to "},{"type":"codeVoice","code":"UFCLoginManager"},{"type":"text","text":". The "},{"type":"codeVoice","code":"PurchaseSDK"},{"type":"text","text":" will ask for login tokens via the "},{"type":"codeVoice","code":"TMPurchaseViewOAuthDelegate"},{"type":"text","text":" and write the results directly to the cookie store"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"true = integrating App will provide feedback to ","type":"text"},{"code":"UFCLoginManager","type":"codeVoice"},{"text":". The ","type":"text"},{"code":"PurchaseSDK","type":"codeVoice"},{"text":" will not call the ","type":"text"},{"code":"TMPurchaseViewOAuthDelegate","type":"codeVoice"},{"text":",","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"It is recommended to leave this flag as "},{"type":"codeVoice","code":"false"},{"text":" for most App integrations","type":"text"}]}]}],"references":{"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPurchase","kind":"identifier"}],"abstract":[{"text":"A class that stores the global configuration for the TicketmasterPurchase SDK.","type":"text"}],"identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase","title":"TMPurchase","url":"\/documentation\/ticketmasterpurchase\/tmpurchase","type":"topic","navigatorTitle":[{"text":"TMPurchase","kind":"identifier"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase/TMPurchase/disableUFCLoginManagement":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase\/TMPurchase\/disableUFCLoginManagement","title":"disableUFCLoginManagement","url":"\/documentation\/ticketmasterpurchase\/tmpurchase\/disableufcloginmanagement","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disableUFCLoginManagement","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Disable UFC login management within the "},{"type":"codeVoice","code":"TicketmasterPurchase SDK"},{"type":"text","text":", the integrating App will handle UFC calls made by the website"}]},"doc://com.ticketmaster.ios.TicketmasterPurchase/documentation/TicketmasterPurchase":{"type":"topic","url":"\/documentation\/ticketmasterpurchase","identifier":"doc:\/\/com.ticketmaster.ios.TicketmasterPurchase\/documentation\/TicketmasterPurchase","abstract":[],"kind":"symbol","title":"TicketmasterPurchase","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchase\/title","value":"TMPurchase"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchase\/fragments","value":[{"kind":"identifier","text":"TMPurchase"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.ios.TicketmasterPurchase~1documentation~1TicketmasterPurchase~1TMPurchase\/navigatorTitle","value":[{"text":"TMPurchase","kind":"identifier"}]}]}]}