{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TMApigeeConfigurationProvider","preciseIdentifier":"s:26TicketmasterAuthentication29TMApigeeConfigurationProviderP"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/configurationProvider"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchase\/configurationprovider"]}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase"]]},"kind":"symbol","abstract":[{"type":"text","text":"Apigee config provider (default: "},{"type":"codeVoice","code":"TMAuthentication.shared"}],"metadata":{"modules":[{"name":"TicketmasterPrePurchase"}],"externalID":"s:23TicketmasterPrePurchase05TMPreC0C21configurationProvider0A14Authentication021TMApigeeConfigurationF0_pvp","role":"symbol","title":"configurationProvider","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TMApigeeConfigurationProvider","preciseIdentifier":"s:26TicketmasterAuthentication29TMApigeeConfigurationProviderP"}],"roleHeading":"Instance Property"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase":{"title":"TMPrePurchase","type":"topic","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPrePurchase","kind":"identifier"}],"navigatorTitle":[{"text":"TMPrePurchase","kind":"identifier"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase","abstract":[{"type":"text","text":"A class that stores the global configuration for the TicketmasterPrePurchase SDK."}]},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","url":"\/documentation\/ticketmasterprepurchase","title":"TicketmasterPrePurchase","role":"collection","abstract":[],"kind":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/configurationProvider":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/configurationProvider","abstract":[{"type":"text","text":"Apigee config provider (default: "},{"type":"codeVoice","code":"TMAuthentication.shared"}],"type":"topic","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/configurationprovider","title":"configurationProvider","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"s:26TicketmasterAuthentication29TMApigeeConfigurationProviderP","kind":"typeIdentifier","text":"TMApigeeConfigurationProvider"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TMPrePurchase","op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/title"},{"value":[{"text":"TMPrePurchase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/fragments"},{"value":[{"kind":"identifier","text":"TMPrePurchase"}],"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/navigatorTitle"}]}]}