{"identifier":{"url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/authenticationProvider","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"authenticationProvider","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TMAuthenticationProvider","preciseIdentifier":"s:26TicketmasterAuthentication24TMAuthenticationProviderP","kind":"typeIdentifier"}],"title":"authenticationProvider","externalID":"s:23TicketmasterPrePurchase05TMPreC0C22authenticationProvider0A14Authentication016TMAuthenticationF0_pvp","modules":[{"name":"TicketmasterPrePurchase"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationProvider","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TMAuthenticationProvider","kind":"typeIdentifier","preciseIdentifier":"s:26TicketmasterAuthentication24TMAuthenticationProviderP"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchase\/authenticationprovider"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Login provider (default: ","type":"text"},{"type":"codeVoice","code":"TMAuthentication.shared"},{"type":"text","text":")"}],"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPrePurchase","kind":"identifier"}],"abstract":[{"text":"A class that stores the global configuration for the TicketmasterPrePurchase SDK.","type":"text"}],"role":"symbol","title":"TMPrePurchase","type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase","navigatorTitle":[{"text":"TMPrePurchase","kind":"identifier"}],"kind":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","type":"topic","abstract":[],"role":"collection","url":"\/documentation\/ticketmasterprepurchase","title":"TicketmasterPrePurchase","kind":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/authenticationProvider":{"role":"symbol","abstract":[{"type":"text","text":"Login provider (default: "},{"type":"codeVoice","code":"TMAuthentication.shared"},{"type":"text","text":")"}],"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/authenticationProvider","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:26TicketmasterAuthentication24TMAuthenticationProviderP","text":"TMAuthenticationProvider"}],"type":"topic","title":"authenticationProvider","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/authenticationprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/title","value":"TMPrePurchase"},{"op":"replace","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/fragments","value":[{"text":"TMPrePurchase","kind":"identifier"}]},{"value":[{"text":"TMPrePurchase","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}