{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"environment"},{"kind":"text","text":": "},{"preciseIdentifier":"s:22TicketmasterFoundation21ConnectionEnvironmentO","kind":"typeIdentifier","text":"ConnectionEnvironment"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"It is recommended to leave this as "},{"code":".production","type":"codeVoice"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/environment"},"kind":"symbol","metadata":{"role":"symbol","externalID":"s:23TicketmasterPrePurchase05TMPreC0C11environment0A10Foundation21ConnectionEnvironmentOvp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"environment","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConnectionEnvironment","kind":"typeIdentifier","preciseIdentifier":"s:22TicketmasterFoundation21ConnectionEnvironmentO"}],"title":"environment","symbolKind":"property","modules":[{"name":"TicketmasterPrePurchase"}],"roleHeading":"Instance Property"},"abstract":[{"text":"The Ticketmaster Host Environment marching the API key provided","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ticketmasterprepurchase\/tmprepurchase\/environment"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase":{"identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase","type":"topic","abstract":[],"role":"collection","url":"\/documentation\/ticketmasterprepurchase","title":"TicketmasterPrePurchase","kind":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase":{"type":"topic","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase","url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TMPrePurchase","kind":"identifier"}],"navigatorTitle":[{"text":"TMPrePurchase","kind":"identifier"}],"abstract":[{"text":"A class that stores the global configuration for the TicketmasterPrePurchase SDK.","type":"text"}],"kind":"symbol","title":"TMPrePurchase","role":"symbol"},"doc://com.ticketmaster.TicketmasterPrePurchase/documentation/TicketmasterPrePurchase/TMPrePurchase/environment":{"title":"environment","identifier":"doc:\/\/com.ticketmaster.TicketmasterPrePurchase\/documentation\/TicketmasterPrePurchase\/TMPrePurchase\/environment","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"environment","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:22TicketmasterFoundation21ConnectionEnvironmentO","kind":"typeIdentifier","text":"ConnectionEnvironment"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The Ticketmaster Host Environment marching the API key provided"}],"url":"\/documentation\/ticketmasterprepurchase\/tmprepurchase\/environment","type":"topic"}},"variantOverrides":[{"patch":[{"value":"TMPrePurchase","path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/title","op":"replace"},{"value":[{"text":"TMPrePurchase","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/fragments","op":"replace"},{"op":"replace","value":[{"text":"TMPrePurchase","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ticketmaster.TicketmasterPrePurchase~1documentation~1TicketmasterPrePurchase~1TMPrePurchase\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}